from app.routers.auth import router as auth_router
from app.routers.user import router as user_router
from app.routers.department import router as department_router
from app.routers.role import router as role_router
from app.routers.permission import router as permission_router
from app.routers.folder import router as folder_router
from app.routers.document import router as document_router
from app.routers.review import router as review_router
from app.routers.favorite import router as favorite_router
from app.routers.ai import router as ai_router
